### PR TITLE
Corrected French translations

### PR DESCRIPTION
**Pull request by XeKrOsu**
Hello ! I've corrected some translations that I found incorrect in the French translation.json file. I don't really know whether these files are still updated or not, but in any case the translations are now good!

### CODE REVIEW

**Comment by M4rti21** [comment]
Thanks! But the translations are handeled through crowdin, sorry its on me for not documenting this right 😓
Do you want me to accept this pull request and add them myself to crowding or do you want to do it? 

PD: yes, the translations are a bit outdated, though some of them will be used for this, im still trying to figure out how to properly implement multi language support

**Comment by M4rti21** [comment]
crowdin here:
https://crowdin.com/project/wysi

**Comment by M4rti21** [comment]
ALSO, sorry for taking this long to respond, i wasnt expecting anyone to submit a pull request so i didnt even check :skull: i appreciate it very much!!!!!

**Comment by XeKrOsu** [comment]
Thanks for the reply and no problem at all! I've copied most of the translations I did here in the crowdin. I've added notes and comments on my translations.

**Comment by M4rti21** [comment]
Thank you so much, i just started working on adding the translations! There are some strings that i removed and i added a bunch more, as the new website has much more stuff than the old version the translations where based one, hopefully i can get this done this weekend!

Closing this issue now

**Pull request closed without merging**
